added new methods for BuildingEndpoint.java
remsfal/remsfal-backend pull request #161
Opened 2024-06-22 07:46 UTC by alexeyleping

https://github.com/remsfal/remsfal-backend/issues/152
added new methods for BuildingEndpoint.java

2024-08-12 08:09 UTC, alexeyleping commented
@astanik hello, ready-made methods for BuildingEndpoint.java, please see how the time will be, is there anything else you need to add?

2024-08-21 10:23 UTC, astanik commented
@alexeyleping Thank you. However, I can't start a review because there are still open conflicts that only you can resolve.

2024-08-21 12:38 UTC, alexeyleping commented
@astanik there are new changes, I will continue to work, I need to finalize the existing code because of this

2024-08-24 12:13 UTC, alexeyleping commented
@astanik New code has appeared and access points have changed, for example, when I make a post request http://localhost:8081/api/v1/projects/projectId/properties/propertiesId/buildings, I expect to create a Building, but now I get an error from the getBuildingResource() Not implemented method, I don't quite understand what it is needed here and how it should be embedded in the logic, can you explain in more detail?

2024-08-31 08:26 UTC, astanik commented
@alexeyleping The stack trace of the create building operation is the following...
ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002010: Failed to execute: jakarta.ws.rs.**InternalServerErrorException: Not implemented**
	**at de.remsfal.service.boundary.project.PropertyResource.getBuildingResource(PropertyResource.java:71)**
	at de.remsfal.service.boundary.project.PropertyResource_ClientProxy.getBuildingResource(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.constructLocator(ResourceLocatorInvoker.java:105)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTargetFromLocator(ResourceLocatorInvoker.java:86)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:137)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invokePropagateNotFound$6(SynchronousDispatcher.java:275)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:260)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:86)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

As you can see, the InternalServerErrorException is thrown in the getBuildingResource() method of the PropertyResource. I will show you the method in a short review.

2024-08-31 08:34 UTC, astanik commented
Just as a note, i would recommend you the implement the tests in the BuildingResourceTest in the project package instead of the boundary package, because in this class you will have example projects and properties already created.

2024-09-02 20:03 UTC, alexeyleping commented
@astanik Question. Now the search is performed by buildingId, whether additional implementation is needed for several parameters ProjectID, PropertyId, buildingId

2024-09-09 12:17 UTC, alexeyleping commented
@astanik  what other tests should I add?

2024-09-17 07:22 UTC, astanik requested changes

2024-09-17 07:22 UTC, astanik commented on remsfal-core/src/main/java/de/remsfal/core/model/AddressModel.java
> +@Value.Immutable
A model is just an interface that defines a common language between our boundary and the entity layer. Therefore, all Immutables and Jackson annotation should only be used in the json package.

2024-09-17 07:22 UTC, astanik commented on remsfal-core/src/main/java/de/remsfal/core/json/project/GarageJson.java
> +    @NotNull
A Garage is a subresource of a building and does not have a separate address.

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
> +public class BuildingResource implements BuildingEndpoint {
The BuildingResource should extend the ProjectSubResource class, because you get some helper methods and objects in order to avoid duplicate code.

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
> +        try {
Please check the user privileges for the project referenced by project id. 
This is the top one security risk listed in OWASP top 10 API, https://owasp.org/API-Security/editions/2023/en/0x11-t10/

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
> +        try {
Please check the user privileges.

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
> +        try {
Please check the user privileges

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/boundary/BuildingResource.java
> +        } catch (WebApplicationException e) {
Don't catch a WebApplicationException, because it already produces the right HTTP status code.

2024-09-17 07:22 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/entity/dto/BuildingEntity.java
> +import jakarta.persistence.*;
Please, don't use the wildcard star import.

2024-09-17 08:09 UTC, alexeyleping commented
Welcome back! Thanks for checking, I'll get to it soon

2024-09-25 10:28 UTC, alexeyleping commented
@astanik I corrected it as it was necessary, please see how the time will be

2024-10-06 15:35 UTC, merged

2024-10-06 15:36 UTC, astanik commented
@alexeyleping Thank you for your contribution!