Add Awaitility Dependency & Import die Bibliothek
remsfal/remsfal-backend pull request #244
Opened 2024-11-11 13:27 UTC by basselali97

2024-11-14 10:48 UTC, astanik requested changes
This is just a preliminary review. A final review follows if the pipeline runs successfully

2024-11-14 10:48 UTC, astanik commented on pom.xml
> +                            <maven.home>${env.MAVEN_HOME}</maven.home>
Please, do not set the maven home in a pom.xml. The maven home is an environment variable that should be provided by the os system.

2024-11-14 10:48 UTC, astanik commented on pom.xml
> +                                    <maven.home>${env.MAVEN_HOME}</maven.home>
Please remove this.

2024-11-14 10:48 UTC, astanik commented on pom.xml
> +    <dependencies>
The dependency is only in the service module required. Therefore, please move this dependency to the remsfal-service/pom.xml

2024-11-19 15:57 UTC, basselali97 commented
Is it working now?

2024-11-20 22:18 UTC, closed without merging