Enhancement/261 complete commercial endpoint functionality
remsfal/remsfal-backend pull request #283
Opened 2024-12-16 15:11 UTC by XxILUSHAxX

Commercial endpoint implemenation

2024-12-17 16:14 UTC, F4c3hugg3r commented
I'd review this pull request in the upcoming days

2024-12-27 22:15 UTC, F4c3hugg3r requested changes
Die meisten Anforderungen des dazugehörigen Issues wurden umgesetzt. Die CRUD Operationen sind vorhanden und überwiegend sehr gut implementiert, allerdings muss der Code fehlerlos kompilierbar werden und die angemerkten Änderungen der Logik bezogen auf das rent Attribut müssen geändert werden. Die im Issue genannte Testabdeckung ist auch nicht vorhanden und sollte ergänzt werden. Für genauere Infos bezüglich der zu machenden Änderungen bitte die Kommentare anschauen.

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dao/CommercialRepository.java
> +    }
Es gibt 2 Implementierungen dieser Methode

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dao/CommercialRepository.java
>      public List<CommercialEntity> findCommercialByBuildingId(String buildingId) {
Es gibt 2 Implementierungen dieser Methode

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dto/CommercialEntity.java
> +
Das sollte gelöscht werden, da die Klasse von RentalUnitEntity erbt, ist der Verweis auf die Tenancy (welche stellvertretend für die rent agiert) bereits implementiert

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dto/CommercialEntity.java
> +    public void setRent(Float rent) {this.rent = rent;}
Das sollte gelöscht werden, da die Klasse von RentalUnitEntity erbt, ist der Verweis auf die Tenancy (welche stellvertretend für die rent agiert) bereits implementiert

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dto/CommercialEntity.java
> +                    && Objects.equals(rent, e.rent);
hier ebenfalls darauf achten, dass es keine rent gibt

2024-12-27 22:15 UTC, F4c3hugg3r commented on remsfal-service/src/main/java/de/remsfal/service/entity/dto/CommercialEntity.java
> +        entity.setRent(commercial.getRent());
hier ebenfalls darauf achten, dass es keine rent gibt

2025-01-06 18:52 UTC, XxILUSHAxX commented
Hello @F4c3hugg3r, i thank you for your constructive feedback, i definetely had some issues which needed to get fixed and i learned as well new things. I took the necessary changes, completed the test classes for the classes used for the Commercial Endpoint and now everything should be perfect. Please take a look at my pull request and let me know if there are any things which i need  to repolish.

2025-01-06 22:52 UTC, F4c3hugg3r approved these changes
Sieht jetzt alles gut aus.

2025-01-07 10:51 UTC, astanik approved these changes
Removed duplicate dependencies and unused field

2025-01-07 10:51 UTC, merged