#267 Implementierung einer Workflow-Engine
remsfal/remsfal-backend pull request #285
Opened 2024-12-16 17:07 UTC by RemodifyBerlin

Dieser Pull Request führt die Integration der Camunda Workflow Engine in einem Docker Container in das Projekt ein. 

Die Änderungen umfassen Aktualisierungen der Datei `README.md`, das Hinzufügen von Camunda-Diensten in `docker-compose.yml` und die Erstellung einer Testklasse für die Demonstration von Camunda-API-Interaktionen.

Camunda-Integration:

* Detaillierte Anweisungen in `README.md` hinzugefügt, wie man Camunda mit Docker betreibt, mit ihm über die REST API interagiert und Tests ausführt.
* Die Datei `docker-compose.yml` wurde aktualisiert, um einen neuen Camunda-Dienst einzubinden, ihn auf Port 8081 freizugeben und ihn so zu konfigurieren, dass Demodaten und Beispielprozesse deaktiviert werden.
* Hinzufügen einer neuen BPMN-Prozessdatei `open-ticket.bpmn`, um einen BeispielWorkflow für das Öffnen eines Tickets zu definieren.
* Hinzufügen einer neuen Testklasse `CamundaApiTest` zur Demonstration der Interaktion mit der Camunda-Engine, einschließlich des Starts von Prozessen und der Ausführung von Aufgaben.
* Aktualisierte `pom.xml`, um `CamundaApiTest` von bestimmten Builds auszuschließen und fügte Abhängigkeiten um REST-Interaktionen zu ermöglichen. 

Der deployde Prozess ist unter dem Camunda Cockpit sichtbar. Hier ist der Prozess zu sehen:

<img width="1164" alt="Bildschirmfoto 2024-12-16 um 17 30 17" src="https://github.com/user-attachments/assets/98ad9187-2c62-44eb-8d61-40d016c41194" />

2024-12-19 07:52 UTC, astanik commented
@RemodifyBerlin Unfortunately I don't see any project integration in this PR?

Take look at https://docs.quarkiverse.io/quarkus-zeebe/dev/index.html or https://docs.camunda.io/docs/apis-tools/community-clients/quarkus/

2024-12-19 15:44 UTC, RemodifyBerlin commented
> @RemodifyBerlin Unfortunately I don't see any project integration in this PR?
> 
> Take look at https://docs.quarkiverse.io/quarkus-zeebe/dev/index.html or https://docs.camunda.io/docs/apis-tools/community-clients/quarkus/

Integrating Camunda Engine with Quarkus proved to be a pain due to runtime errors, version conflicts, and database configuration requirements for camunda (READ_COMMITTED) that disrupted tests and services. 

I should have read more into the limitations of quarkus and camunda ([here](https://docs.camunda.org/manual/7.22/user-guide/quarkus-integration/cdi-integration)) and read more experiences about the integration, which are mixed. 

Refactoring the project to accommodate these issues felt unnecessary for a simple proof of concept designed to demonstrate the potential of a workflow engine. The limited community support further compounded the delays, and I couldn’t find solutions within the available timeframe. 

To move forward and finish this feature, I switched to using Docker for Camunda Engine, providing a simpler, more flexible setup.

I hope my approach offers atleast valuable insights for future developers tackling this in the project.

2024-12-31 18:27 UTC, gflachs reviewed
Ein Review dieses PR ist schwieirig, da er nicht zu der im Issue beschriebenen Lösung beiträgt und auch keine Integration in das Projekt beinhaltet.

Basierend auf dem im Issue beschrieben Ziel und dem von @astanik bereits verlinkten Ressourcen habe ich einmal ein Testsetup erstellt, welches das Problem lösen sollte. Ich werde dieses hier nun beschreiben, sodass Du @RemodifyBerlin die Möglichkeit hast, Deinen PR eventuell noch anzupassen und Deine an sich sehr guten Ansätze in das Projekt integrieren zu können.

Die Lösung baisert dabei auf Zeebe, der Cloud-nativen, eventgesteuerten Lösung von Camunda (https://camunda.com/de/platform/zeebe/) und der Dokumentation von diesem (https://docs.quarkiverse.io/quarkus-zeebe/dev/index.html):

Zuerst muss in der pom.xml folgende Dependency hinzugefügt werden:
```xml
<dependency>
            <groupId>io.quarkiverse.zeebe</groupId>
            <artifactId>quarkus-zeebe</artifactId>
            <version>1.6.0</version>
        </dependency>
```
        
Diese Dependency fügt den Zeebie-Client, sowie den Worker hinzu und bietet die Möglichkeit innerhalb des Codes BPMN auszuführen. Damit eine Verbindung zum Zeebe-Worker hergestellt werden kann, muss im nächsten Schritt ein Zeebe-Container mithilfe der Docker-Compose deployed werden:

```docker compose
  zeebe:
    image: camunda/zeebe:latest
    ports:
      - "26500:26500" # gRPC-Port für Client-Verbindungen
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1
 ```
  
  Folgende properties wurden aus dem oben erwähnten Tutorial übernommen und sollten eventuell angepasst werden:
 
```
quarkus.zeebe.resources.enabled=true
quarkus.zeebe.resources.location=bpmn
quarkus.zeebe.devservices.enabled=true
quarkus.zeebe.devservices.shared=true
quarkus.zeebe.devservices.service-name=zeebe_broker
quarkus.zeebe.devservices.reuse=false
quarkus.zeebe.dev-mode.watch-bpmn-dir=true
quarkus.zeebe.dev-mode.watch-bpmn-files=true
quarkus.zeebe.dev-mode.watch-job-worker=true
```

Diese Einstellungen sorgen dafür, dass die im src/main/ressources/bpmn befindlichen bpmn Dateien automatisch in Zeebe deployed werden.
Innerhalb dieses Ordners können nun also entsprechende BPMN-Files abgelegt werden. Als einfache Demonstration habe ich mich hier für folgendes BPMN entschieden:

![image](https://github.com/user-attachments/assets/20d1c2b1-27a4-490f-a91f-877dce4b6b9f)

Hierbei ist vor allem die id der einzelnen Tasks wichtig, da diese später für die JobWorker benötigt werden. Die Ids können entweder in der XML direkt gefunden werden (bpmn:process id="id") oder im Modeller gesetzt werden.

Um den Workflow nun starten zu können, reicht ein einfacher Controller:
```java
package de.remsfal.service.control;

import io.camunda.zeebe.client.ZeebeClient;
import jakarta.inject.Inject;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.QueryParam;

import java.util.Map;

@Path("/zeebe")
public class ZeebeController {

    @Inject
    ZeebeClient zeebeClient;

    @Path("/start")
    public String startWorkflow(@QueryParam("decision") String decision) {

        Map<String, Object> variables = Map.of("decision", decision);

        var workflowInstance = zeebeClient.newCreateInstanceCommand()
                .bpmnProcessId("decisionProcess")
                .latestVersion()
                .variables(variables)
                .send()
                .join();

        return "Workflow instance started with key: " + workflowInstance.getProcessInstanceKey();

    }
}
```
Dieser Controller startet nun meinen oben erwähten Beispielworkflow.

Damit der Workflow ordentlich abgearbeitet werden kann, ist es noch notwendig einzelne JobWorker für die entsprechenden Prozessschritte zu definieren:

```
package de.remsfal.service.zeebe;


import io.camunda.zeebe.client.api.response.ActivatedJob;
import io.camunda.zeebe.client.api.worker.JobClient;
import io.quarkiverse.zeebe.JobWorker;
import jakarta.inject.Inject;
import org.jboss.logging.Logger;


public class ZeebeWorker {

    @Inject
    Logger logger;

    @JobWorker(type = "yesTask")
    public void yesTaskHandler(final JobClient client, final ActivatedJob job) {
        logger.info("Yes task handler called");
        client.newCompleteCommand(job.getKey()).send().join();
    }

    @JobWorker(type = "noTask")
    public void noTaskHandler(final JobClient client, final ActivatedJob job) {
        logger.info("No task handler called");
        client.newCompleteCommand(job.getKey()).send().join();
    }

}
```

Mithilfe dieses einfachen Setups ist es möglich eine Workflow-Engine zu integrieren.

Wenn Du das entsprechend für Deinen Ticketworkflow anpasst, kann auch eine Integration in das Projekt erfolgen

2025-01-04 13:13 UTC, RemodifyBerlin commented
@gflachs @astanik Thank you both for the thorough review and the helpful references! I was too focused on getting Camunda 7 working with Quarkus that I overlooked the possibility of integrating with Zeebe. 

I really appreciate you pointing me in that direction and providing the test setup. Before this, I wasn’t aware of Zeebe at all, so that was a great learning experience. I believe this update should now meet all the requirements. Thanks again for pointing me in the right direction!

2025-01-06 07:40 UTC, RemodifyBerlin commented
@gflachs @astanik Could you please review it one more time so I have enough time to make any necessary adjustments before the deadline?

2025-01-06 07:53 UTC, gflachs commented
> @gflachs @astanik Could you please review it one more time so I have enough time to make any necessary adjustments before the deadline?

@astanik Ich bräuchte bitte nochmal das Recht zu reviewen, ich kann aktuell kein Review hinterlassen

2025-01-06 17:13 UTC, gflachs requested changes
Vielen Dank für das Umsetzen des Feedbacks. Die JobWorker könnten noch generischer gestaltet werden (z.B. einen generellen JobWorker für das prüfen von approvals etc.), es ist aber ein erster guter Ansatz. Allerdings fehlen mir hier noch die im Issue beschrieben Schritte des Workflows:

> Bei Bedarf werden Rückfragen oder zusätzliche Informationen im Prozess berücksichtigt. (Entscheidungsgateway)
3A Der zuständige Mitarbeiter anwortet
3B Es wird zum Endtask navigiert
>Abschluss:
Das Ticket wird als gelöst markiert, und der Kunde oder das Team wird informiert.

Diese sollten noch implementiert werden

2025-01-06 17:13 UTC, gflachs commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +        public String startWorkflow(@QueryParam("approve") Boolean approve) {
Lass Dir doch hier auch noch di Workflow-Id mit übergeben, sodass mithilfe des /start Endpunkts  beliebige Workflows gestartet werden können. Aus den Queryparams kannst Du Dir dann eine Map machen und diese je nach Workflows auslesen

2025-01-06 17:13 UTC, gflachs commented on README.md
Bitte beeschreibe noch ausführlicher die eeinzelnen Funktionen. Wenn dieser Workflow aktuell nur dafür genutzt werden soll, um anderen nachher die Arbeit leichter zu machen, wäre es recht nützlich hier eine ausführliche Beschreibung zu erhalten, wo ich was finde (z.B: was ist ein JobWorker, wo ist der definiert etc.)

2025-01-06 17:13 UTC, gflachs commented on remsfal-service/src/main/resources/application.properties
Bitte prüfe noch einmal die zeebe config. Hier sind sogagr noch reine dev-mode Sachen aktiviert, welche inn Produktion nicht genutzt werden sollten.
Zusätzlich gibt es von Quarkus selber Vorschläge dazu, welche Einstellungen verwendet werden sollten.

2025-01-07 16:38 UTC, RemodifyBerlin commented
@gflachs Danke für dein Review! 

Die genannten Punkte wurden soweit umgesetzt. Zu deinem Punkt: „(...) Diese Schritte sollten noch implementiert werden.“ – Der erste Prozess war ein initiales Konzept, das eine Entscheidung und Variablen beinhaltet. Ziel war es, einen einfachen Prozess darzustellen. 

Für das erste Konzept wäre es erforderlich gewesen, unnötige Logik zu simulieren, was nicht zielführend ist. Deswegen habe ich es in einen Ticket-Prozess umgewandelt, bei dem ein Mitarbeiter über den Ticket-Prozess entscheidet und so die Zeebe-Funktionen gezeigt werden. 

Ich hoffe, es passt! Lass mich wissen, falls du weitere Anmerkungen hast.

2025-01-07 22:14 UTC, gflachs approved these changes

2025-01-08 08:39 UTC, RemodifyBerlin commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +                                        .build();
Ich habe es hier mit einem Templated String gelöst.

2025-01-08 08:41 UTC, astanik approved these changes
This is a pioneering achievement in terms of processing in remstal. Feel free to create issues for my review points.

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/test/java/de/remsfal/service/control/ZeebeControllerTest.java
> +    @Mock
The main logic is mocked, may be because devservices are not enabled while testing.

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/test/java/de/remsfal/service/control/ZeebeControllerTest.java
> +        Response response = controller.startWorkflow(requestBody);
This is not an integration test and the REST API with its authentication have not been tested.

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/zeebe/ZeebeWorker.java
> +package de.remsfal.service.zeebe;
Zeebe worker should be part of the control layer.

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +                        .build();
true

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +                                        .build();
true

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +@Path("/zeebe")
The REST API should be in the boundary layer.

2025-01-08 08:41 UTC, astanik commented on remsfal-service/src/main/java/de/remsfal/service/control/ZeebeController.java
> +        public Response startWorkflow(Map<String, Object> requestBody) {
It would be much more readable if the json body was implemented as a java class, e.g. remsfal-core/src/main/java/de/remsfal/core/json/**/*Json.java

2025-01-08 08:42 UTC, merged