#265 Implementierung des Garage Endpoints mit CRUD-Funktionalität
remsfal/remsfal-backend pull request #287
Opened 2024-12-17 15:06 UTC by Eyad-Wahdan

### **Pull Request Description**  

This PR implements the `Garage` endpoint, providing full CRUD functionality as defined in **[Issue #265](https://github.com/remsfal/remsfal-backend/issues/265)**

### **Key Changes**  
- **Core Package**: Implemented `GarageEndpoint`, `GarageJson`, and `GarageModel` with specified attributes
- **Service Package**: Implemented `GarageResource`, `GarageController`, `GarageRepository`, and `GarageEntity` for managing Garage data
- **Testing**: Added tests for CRUD endpoints and validated business logic

This ensures full CRUD operations for the Garage Entity with proper definitions and database integration

2024-12-29 07:07 UTC, RemodifyBerlin requested changes
Overall, this is a great job! 

The code is well-organized, and the functionality is clear. There are only a few minor issues to tidy up (or check) before merging—for example, some duplicated code and slight naming inconsistencies. With a quick cleanup, the code will be easier to maintain in the future. Then you should be good to go to merge!

2024-12-29 07:07 UTC, RemodifyBerlin commented on remsfal-service/src/test/java/de/remsfal/service/boundary/project/GarageResourceTest.java
> +        final String projectId = given()
A lot of repeated steps for creating a project → property → building → then the garage in each test method. Consider extracting common setup logic into helper method, to reduce code redundancy

2024-12-29 07:07 UTC, RemodifyBerlin commented on remsfal-service/src/test/java/de/remsfal/service/control/GarageControllerTest.java
> +        final BuildingModel building = TestData.buildingBuilder()
See above: A lot of repeated steps for each test method. Consider extracting common setup logic into helper method, to reduce code redundancy and shorten the test class

2025-01-04 13:48 UTC, Eyad-Wahdan commented on remsfal-service/src/main/java/de/remsfal/service/boundary/project/GarageResource.java
> +    GarageController controller;
Thank you for the suggestion! That’s a good point, and I appreciate the attention to clarity. In this case, the variable controller is scoped to the GarageResource class, and no other controllers are used here. I also reviewed the other resource classes, and this naming approach is consistently used across them. To maintain consistency with the existing convention, I’d prefer keeping it unchanged. Thanks again for the thoughtful input!

2025-01-04 14:01 UTC, Eyad-Wahdan commented on remsfal-core/src/main/java/de/remsfal/core/json/project/GarageJson.java
> +            return null;
I understand the concern about null propagation and agree that returning an empty/invalid object or throwing an exception could help enforce stricter handling of null values. However, in this specific case, the method's purpose is to map the GarageModel to GarageJson, even when certain fields are null. Returning null for the entire object ensures that the caller has full control over how null values are handled downstream, making the behavior predictable and flexible. Additionally, I reviewed the other Json-classes, and they follow the same approach, so maintaining consistency across the codebase is preferable. Thanks for the suggestion!

2025-01-04 14:11 UTC, Eyad-Wahdan commented on remsfal-service/src/main/java/de/remsfal/service/control/GarageController.java
> +        logger.infov("Creating a garage (projectId={0}, buildingId={1}, garage={2})",
Thank you for the suggestion! I understand the concern regarding sensitive data exposure. However, in this case, logging the entire GarageModel provides valuable context for debugging and tracking the flow of data, especially when creating a new garage. Since the logging is used for development and debugging purposes, it's important to capture the full model. On the other hand, when retrieving a garage from the database, only the garageId is logged for data protection purposes. I reviewed the other controller classes, and they handle logging in a similar manner, so I believe keeping this approach ensures consistency across the codebase.

2025-01-05 23:17 UTC, Eyad-Wahdan commented on remsfal-service/src/test/java/de/remsfal/service/boundary/project/GarageResourceTest.java
> +        final String projectId = given()
Thank you for the suggestion, done!

2025-01-05 23:37 UTC, Eyad-Wahdan commented on remsfal-service/src/test/java/de/remsfal/service/control/GarageControllerTest.java
> +        final BuildingModel building = TestData.buildingBuilder()
Thank you for the suggestion, done!

2025-01-06 07:45 UTC, RemodifyBerlin commented on remsfal-service/src/main/java/de/remsfal/service/control/GarageController.java
> +        logger.infov("Creating a garage (projectId={0}, buildingId={1}, garage={2})",
Thanks for clarifying! If it’s handled the same way in the other controller classes and you’re mindful of sensitive data, then that sounds fine. Just make sure no private information is being logged.

2025-01-06 07:47 UTC, RemodifyBerlin commented on remsfal-core/src/main/java/de/remsfal/core/json/project/GarageJson.java
> +            return null;
ok if the codebase consistently handles null values this way, sticking to the same approach makes sense.

2025-01-06 07:48 UTC, RemodifyBerlin commented on remsfal-service/src/main/java/de/remsfal/service/boundary/project/GarageResource.java
> +    GarageController controller;
ok if the codebase consistently handles naming this way, sticking to the same approach makes sense.

2025-01-06 07:49 UTC, RemodifyBerlin approved these changes
Good work, and thanks for addressing all the points.

2025-01-06 07:50 UTC, RemodifyBerlin approved these changes

2025-01-06 13:00 UTC, astanik approved these changes

2025-01-06 13:01 UTC, merged